#!/usr/bin/env python3
"""Train and evaluate a free-generation proof-fragment SFT branch.

The training packet contains only verified TRAIN proof fragments. DEVELOPMENT
rows retain their frozen theorem scaffolds but have all answer-bearing fields
removed before staging.  The worker emits raw base/parent/child generations;
an independent strict TLAPS scorer decides whether any exact generated bytes
certify.  No verifier feedback, reward, repair, ranking, or DEVELOPMENT proof
bytes enter training.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import time


ANSWER_FIELDS = {
    "reference_fragment", "proof_body", "pir_target", "candidate", "response",
    "generated", "repair", "feedback", "tlaps_output", "reward",
}
PUBLIC_DEVELOPMENT_FIELDS = {
    "id", "split", "source_family", "source_sha256", "assembled_sha256",
    "prefix", "suffix", "theorem_name", "module_name", "dependencies",
    "standard_dependencies", "dependency_sha256", "task_contract",
}


def digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def dump(path: Path, value) -> None:
    path.write_text(json.dumps(value, indent=2) + "\n")


def prompt_for(task: dict) -> str:
    return (
        "Complete the missing TLA+ proof fragment marked <PROOF_HOLE>. "
        "The theorem statement and all other proof steps are fixed. "
        "Return only the missing proof fragment, preferably in a tla code fence. "
        "Use valid TLAPS syntax. Do not introduce axioms, omit proofs, change "
        "definitions, or repeat the module.\n\n"
        + task["prefix"] + "<PROOF_HOLE>" + task["suffix"]
    )


_FENCE = re.compile(r"```(?:tla|tlaplus|tla\+)?\s*\n(.*?)```", re.DOTALL | re.IGNORECASE)
_START = re.compile(r"^\s*(PROOF\b|<\d+>|BY\b|OBVIOUS\b|OMITTED\b)")


def extract_proof_block(reply: str) -> str | None:
    if not reply:
        return None
    fenced = _FENCE.search(reply)
    if fenced:
        candidate = fenced.group(1).strip()
        if candidate and _START.match(candidate):
            return candidate
    lines = reply.splitlines()
    for index, line in enumerate(lines):
        if _START.match(line):
            candidate = "\n".join(lines[index:]).strip()
            if candidate:
                return candidate
    return None


def _validate_task_shape(task: dict, *, needs_reference: bool) -> None:
    required = {"id", "split", "source_family", "source_sha256", "assembled_sha256",
                "prefix", "suffix", "theorem_name", "dependencies"}
    missing = required - set(task)
    if missing:
        raise ValueError(f"task {task.get('id')} missing fields: {sorted(missing)}")
    if needs_reference and not isinstance(task.get("reference_fragment"), str):
        raise ValueError(f"train task {task['id']} lacks reference_fragment")
    if not needs_reference and any(key in task for key in ANSWER_FIELDS):
        raise ValueError(f"development task {task['id']} contains answer-bearing fields")


def prepare_manifest(source: Path, output: Path) -> dict:
    """Create the model-visible packet with DEVELOPMENT answers removed."""
    source_data = json.loads(source.read_text())
    tasks = source_data.get("tasks")
    if not isinstance(tasks, list) or len({t.get("id") for t in tasks}) != len(tasks):
        raise ValueError("manifest tasks must be a nonempty unique list")
    train = [t for t in tasks if t.get("split") == "train"]
    development = [t for t in tasks if t.get("split") == "development"]
    if len(train) != 17 or len(development) != 4:
        raise ValueError(f"expected 17 train and 4 development tasks, got {len(train)} and {len(development)}")
    for task in train:
        _validate_task_shape(task, needs_reference=True)
    public_dev = []
    for task in development:
        _validate_task_shape(task, needs_reference=False) if not any(k in task for k in ANSWER_FIELDS) else None
        if "reference_fragment" not in task:
            raise ValueError(f"source development task {task['id']} lacks frozen reference for source audit")
        sanitized = {key: task[key] for key in PUBLIC_DEVELOPMENT_FIELDS if key in task}
        sanitized["split"] = "development"
        _validate_task_shape(sanitized, needs_reference=False)
        public_dev.append(sanitized)
    # Train is private by design and contains only the supervised fields plus
    # frozen metadata.  DEVELOPMENT is strictly reduced to prompt/scaffold data.
    clean = {key: value for key, value in source_data.items()
             if key not in {"development_context_sources", "official_sources"}}
    clean["tasks"] = train + public_dev
    clean["development_context_sources"] = []
    clean["scope"] = "free-generation teacher-forced SFT; DEVELOPMENT answers removed before staging"
    clean["answer_fields_removed_from_development"] = sorted(ANSWER_FIELDS)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(clean, indent=2) + "\n")
    raw = output.read_bytes()
    return {
        "manifest_sha256": digest(raw),
        "train_tasks": len(train),
        "development_tasks": len(public_dev),
        "development_reference_bytes_forwarded": False,
        "answer_fields_removed": sorted(ANSWER_FIELDS),
    }


def training_tasks(manifest: dict) -> tuple[list[dict], list[dict]]:
    tasks = manifest.get("tasks")
    if not isinstance(tasks, list) or len({t.get("id") for t in tasks}) != len(tasks):
        raise ValueError("tasks must be a unique list")
    train = [task for task in tasks if task.get("split") == "train"]
    development = [task for task in tasks if task.get("split") == "development"]
    if len(train) != 17 or len(development) != 4:
        raise ValueError("manifest must contain exactly 17 train and 4 development tasks")
    for task in train:
        _validate_task_shape(task, needs_reference=True)
    for task in development:
        _validate_task_shape(task, needs_reference=False)
    if {t["source_family"] for t in train} & {t["source_family"] for t in development}:
        raise ValueError("train/development source-family overlap")
    if {(t["prefix"], t["suffix"]) for t in train} & {(t["prefix"], t["suffix"]) for t in development}:
        raise ValueError("train/development scaffold overlap")
    return train, development


def restore_trainable(trainable: dict, saved: dict, device) -> None:
    import torch
    state = saved.get("trainable_state")
    if not isinstance(state, dict) or set(state) != set(trainable):
        raise ValueError("checkpoint trainable parameter coverage mismatch")
    with torch.no_grad():
        for name, parameter in trainable.items():
            if state[name].shape != parameter.shape or state[name].dtype != parameter.dtype:
                raise ValueError(f"checkpoint shape/dtype mismatch: {name}")
            parameter.copy_(state[name].to(device))


def generate_policy(net, tokenizer, tasks, policy: str, device, max_tokens: int) -> list[dict]:
    import torch
    rows = []
    for task in tasks:
        prompt = prompt_for(task)
        rendered = tokenizer.apply_chat_template(
            [dict(role="user", content=prompt)], tokenize=False, add_generation_prompt=True)
        encoded = tokenizer(rendered, return_tensors="pt").to(device)
        started = time.monotonic()
        with torch.inference_mode():
            output = net.generate(
                **encoded, max_new_tokens=max_tokens, do_sample=False,
                pad_token_id=tokenizer.eos_token_id, use_cache=True)
        ids = output[0, encoded.input_ids.shape[1]:].tolist()
        raw_reply = tokenizer.decode(ids, skip_special_tokens=True)
        rows.append({
            "policy": policy, "task": task["id"], "prompt": prompt,
            "rendered_prompt": rendered, "raw_reply": raw_reply,
            "token_ids": ids, "input_tokens": int(encoded.input_ids.shape[1]),
            "output_tokens": len(ids), "fragment": extract_proof_block(raw_reply),
            "generation_seconds": time.monotonic() - started,
        })
    return rows


def train(args) -> dict:
    import torch
    import transformers

    started = time.monotonic()
    manifest_raw = args.manifest.read_bytes()
    train, development = training_tasks(json.loads(manifest_raw))
    if args.output.exists():
        raise ValueError("output already exists")
    args.output.mkdir(parents=True)
    (args.output / "manifest.json").write_bytes(manifest_raw)
    os.environ.update(HF_HUB_OFFLINE="1", TRANSFORMERS_OFFLINE="1", TOKENIZERS_PARALLELISM="false")
    torch.set_num_threads(4)
    torch.manual_seed(args.seed)
    tokenizer = transformers.AutoTokenizer.from_pretrained(args.model_path, local_files_only=True)
    net = transformers.AutoModelForCausalLM.from_pretrained(
        args.model_path, local_files_only=True, torch_dtype=torch.float32).to(args.device).eval()
    net.requires_grad_(False)
    net.model.layers[-1].requires_grad_(True)
    trainable = {name: p for name, p in net.named_parameters() if p.requires_grad}
    parent = torch.load(args.parent_checkpoint, map_location="cpu", weights_only=False)
    restore_trainable(trainable, parent, args.device)
    optimizer = torch.optim.AdamW(trainable.values(), lr=args.lr, weight_decay=0)
    config = {
        "args": {k: str(v) if isinstance(v, Path) else v for k, v in vars(args).items()},
        "manifest_sha256": digest(manifest_raw),
        "parent_checkpoint_sha256": digest(args.parent_checkpoint.read_bytes()),
        "algorithm": "response-only causal cross-entropy SFT from exact parent trainable state",
        "scope": "free-generation proof fragments; strict external TLAPS evaluation required",
        "train_ids": [task["id"] for task in train],
        "development_ids": [task["id"] for task in development],
        "development_reference_bytes_forwarded": False,
        "optimizer_updates": 0,
        "torch_version": torch.__version__,
        "transformers_version": transformers.__version__,
    }
    dump(args.output / "config.json", config)

    net.requires_grad_(False)
    base_rows = generate_policy(net, tokenizer, development, "base", args.device, args.max_tokens)
    restore_trainable(trainable, parent, args.device)
    parent_rows = generate_policy(net, tokenizer, development, "parent", args.device, args.max_tokens)
    net.model.layers[-1].requires_grad_(True)
    metrics = []
    with (args.output / "steps.jsonl").open("x") as ledger:
        for step in range(args.steps):
            if time.monotonic() - started >= args.seconds:
                break
            task = train[step % len(train)]
            prompt = prompt_for(task)
            rendered = tokenizer.apply_chat_template(
                [dict(role="user", content=prompt)], tokenize=False, add_generation_prompt=True)
            full = tokenizer.apply_chat_template(
                [dict(role="user", content=prompt), dict(role="assistant", content=task["reference_fragment"])],
                tokenize=False, add_generation_prompt=False)
            prefix_ids = tokenizer(rendered, add_special_tokens=False, truncation=False)["input_ids"]
            ids = tokenizer(full, add_special_tokens=False, truncation=False)["input_ids"]
            if not full.startswith(rendered) or ids[:len(prefix_ids)] != prefix_ids:
                raise ValueError("chat template moved supervised response boundary")
            response = ids[len(prefix_ids):]
            if tokenizer.eos_token_id not in response:
                raise ValueError("training response lacks EOS")
            response = response[:response.index(tokenizer.eos_token_id) + 1]
            ids = prefix_ids + response
            if len(ids) > args.max_sequence_tokens:
                raise ValueError("training sequence exceeds max_sequence_tokens")
            labels = [-100] * len(prefix_ids) + ids[len(prefix_ids):]
            input_ids = torch.tensor([ids], device=args.device)
            label_ids = torch.tensor([labels], device=args.device)
            optimizer.zero_grad(set_to_none=True)
            result = net(input_ids=input_ids, labels=label_ids, use_cache=False)
            loss = result.loss
            if not torch.isfinite(loss):
                raise RuntimeError("nonfinite loss")
            loss.backward()
            norm = torch.nn.utils.clip_grad_norm_(trainable.values(), 1.0, error_if_nonfinite=True)
            optimizer.step()
            row = {"step": step + 1, "task": task["id"], "loss": float(loss.detach()),
                   "gradient_norm": float(norm), "response_tokens": len(response),
                   "elapsed_s": time.monotonic() - started}
            metrics.append(row)
            ledger.write(json.dumps(row) + "\n")
            ledger.flush()
            print(json.dumps(row), flush=True)
    state = {name: parameter.detach().cpu().clone() for name, parameter in trainable.items()}
    scratch = args.output / "policy_weights.partial.pt"
    final = args.output / "policy_weights.pt"
    torch.save({"trainable_state": state, "config": config, "metrics": metrics}, scratch)
    os.replace(scratch, final)
    checkpoint_sha = digest(final.read_bytes())
    net.requires_grad_(False)
    child_rows = generate_policy(net, tokenizer, development, "child", args.device, args.max_tokens)
    rows = base_rows + parent_rows + child_rows
    with (args.output / "generations.jsonl").open("x") as stream:
        for row in rows:
            stream.write(json.dumps(row) + "\n")
    summary = {
        "schema": 1, "manifest_sha256": digest(manifest_raw),
        "parent_checkpoint_sha256": digest(args.parent_checkpoint.read_bytes()),
        "child_checkpoint_sha256": checkpoint_sha, "updates": len(metrics),
        "requested_updates": args.steps, "train_tasks": len(train),
        "development_tasks": len(development), "generation_rows": len(rows),
        "development_reference_bytes_forwarded": False, "verifier_feedback_used": False,
        "reward_used": False, "optimizer_updates": len(metrics),
        "elapsed_seconds": time.monotonic() - started,
        "quality_claim": False, "proof_claim": False, "gate_claim": False,
    }
    dump(args.output / "summary.json", summary)
    print(json.dumps(summary), flush=True)
    return summary


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="mode", required=True)
    prep = sub.add_parser("prepare")
    prep.add_argument("--source", type=Path, required=True)
    prep.add_argument("--output", type=Path, required=True)
    preflight = sub.add_parser("preflight")
    preflight.add_argument("--manifest", type=Path, required=True)
    train_parser = sub.add_parser("train")
    train_parser.add_argument("--manifest", type=Path, required=True)
    train_parser.add_argument("--model-path", type=Path, required=True)
    train_parser.add_argument("--parent-checkpoint", type=Path, required=True)
    train_parser.add_argument("--output", type=Path, required=True)
    train_parser.add_argument("--device", choices=["cpu", "cuda"], default="cuda")
    train_parser.add_argument("--steps", type=int, default=17)
    train_parser.add_argument("--seconds", type=int, default=780)
    train_parser.add_argument("--max-tokens", type=int, default=256)
    train_parser.add_argument("--max-sequence-tokens", type=int, default=10000)
    train_parser.add_argument("--seed", type=int, default=20260917)
    train_parser.add_argument("--lr", type=float, default=1e-5)
    args = parser.parse_args()
    if args.mode == "prepare":
        print(json.dumps(prepare_manifest(args.source, args.output), indent=2))
    elif args.mode == "preflight":
        train_rows, development_rows = training_tasks(json.loads(args.manifest.read_text()))
        print(json.dumps({"train_tasks": len(train_rows), "development_tasks": len(development_rows),
                          "development_reference_bytes_forwarded": False,
                          "model_loaded": False, "cuda_touched": False,
                          "optimizer_updates": 0}, indent=2))
    else:
        if args.steps < 1 or args.seconds < 1 or args.max_tokens < 1 or args.lr <= 0:
            parser.error("invalid training bounds")
        train(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
